# random comment to test workflow
name: "dockerBuild"
description: "setup docker build, cache docker layers, register on fly, create database branch, docker build"
inputs:
  APP_NAME:
    required: true
    description: "the app name"
  PLANETSCALE_SERVICE_TOKEN_ID:
    required: true
    description: "planetscale service token id"
  PLANETSCALE_SERVICE_TOKEN:
    required: true
    description: "planetscale service token"
  ORG_NAME:
    required: true
    description: "Organisation name"
    default: Demo
  DB_NAME:
    required: true
    description: "DB name"
  BRANCH_NAME:
    required: false
    description: "Branch name"
  FROM:
    description: "The branch to clone from"
  PASSWORD_NAME:
    required: true
    description: "the name of the password in planetscale"
  FLY_API_TOKEN:
    required: true
    description: "fly.io api token"
  VAPID_PUBLIC_KEY:
    required: true
    description: "remix pwa public key"
    default: Demo
  VAPID_PRIVATE_KEY:
    required: true
    description: "remix pwa private key"
  SANITY_STUDIO_API_DATASET:
    required: true
    description: "content from sanity"
  SANITY_STUDIO_API_PROJECT_ID:
    required: true
    description: "id of content from sanity"
  SANITY_STUDIO_API_TOKEN:
    required: true
    description: "sanity api token"
  ALGOLIA_APP_ID:
    required: true
    description: "the app id for algolia"
  ALGOLIA_ID_SEARCH_ONLY_API_KEY:
    required: true
    description: "the search only api key for algolia"
  ALGOLIA_PRIMARY_INDEX:
    required: true
    description: "the primary index to query with autcomplete"
  ALGOLIA_PRIMARY_INDEX_GROUPED:
    required: true
    description: "the primary index to query with autcomplete (grouped variants)"
  ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS:
    required: true
    description: "the primary index to query with autcomplete (query suggestions)"
  INSTANT_SEARCH_INDEX_NAME:
    required: true
    description: "the main index name"
  INSTANT_SEARCH_QUERY_SUGGESTIONS:
    required: true
    description: "the query suggestions index name"
  HUBSPOT_ACCESS_TOKEN:
    required: true
    description: "hubspot access token"
  HUBSPOT_PORTAL_ID:
    required: true
    description: "hubspot portal id"
  PUBLIC_STOREFRONT_API_TOKEN:
    required: true
    description: "public storefront api token"
  PRIVATE_STOREFRONT_API_TOKEN:
    required: true
    description: "private storefront api token"
  PUBLIC_STOREFRONT_API_VERSION:
    required: true
    description: "public storefront api version"
  PUBLIC_STORE_DOMAIN:
    required: true
    description: "public storefront domain"
runs:
  using: "composite"
  steps:
    - name: format head_ref
      uses: bluwy/substitute-string-action@v1
      id: findandreplace
      with:
        _input-text: ${{ github.head_ref }}
        /: "-"

    - name: Get PR details
      shell: bash
      run: |
        echo "HEAD_REF=${{ steps.findandreplace.outputs.result }}" >> $GITHUB_ENV
        echo "BASE_REF=${{ github.base_ref  }}" >> $GITHUB_ENV
        echo "PR_CLOSED=${{ github.event.pull_request.merged == true }}" >> $GITHUB_ENV

    # from here
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: v0.9.1

    # Setup cache
    - name: ⚡️ Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: 🔑 Fly Registry Auth
      uses: docker/login-action@v1
      with:
        registry: registry.fly.io
        username: x
        password: ${{ inputs.FLY_API_TOKEN }}

    - name: create connection string to STAGING
      shell: bash
      if: ${{ inputs.BRANCH_NAME }}
      id: create-cs
      env:
        PLANETSCALE_SERVICE_TOKEN_ID: ${{inputs.PLANETSCALE_SERVICE_TOKEN_ID}}
        PLANETSCALE_SERVICE_TOKEN: ${{inputs.PLANETSCALE_SERVICE_TOKEN}}
        ORG_NAME: ${{inputs.ORG_NAME}}
        DB_NAME: ${{inputs.DB_NAME}}
        GITHUB_USER: ${{github.actor}}
        BRANCH_NAME: ${{inputs.BRANCH_NAME }}
        PASSWORD_NAME: staging-${{ inputs.PASSWORD_NAME }}
      run: |
        ./.pscale/cli-helper-scripts/create-branch-connection-string-pr-branches.sh

    - name: create connection string to MAIN
      shell: bash
      id: create-cs-main
      if: ${{ env.BASE_REF == 'main' && env.PR_CLOSED == 'true' && inputs.BRANCH_NAME }}
      env:
        PLANETSCALE_SERVICE_TOKEN_ID: ${{inputs.PLANETSCALE_SERVICE_TOKEN_ID}}
        PLANETSCALE_SERVICE_TOKEN: ${{inputs.PLANETSCALE_SERVICE_TOKEN}}
        ORG_NAME: ${{inputs.ORG_NAME}}
        DB_NAME: ${{inputs.DB_NAME}}
        GITHUB_USER: ${{github.actor}}
        BRANCH_NAME: ${{inputs.BRANCH_NAME }}
        PASSWORD_NAME: main-${{ inputs.PASSWORD_NAME }}
      run: |
        ./.pscale/cli-helper-scripts/create-branch-connection-string.sh

    # we have two versions of docker build, in each one we
    # need to pass in different Planetscale prisma database urls && files to each docker build command
    - name: 🐳 Docker build Production
      id: docker-build-prod
      if: ${{ env.BASE_REF == 'main' && env.PR_CLOSED == 'true' && inputs.BRANCH_NAME }}
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfiles/Dockerfile
        context: .
        push: true
        tags: registry.fly.io/${{ inputs.APP_NAME }}:${{ env.HEAD_REF }}-${{ github.sha }}
        build-args: |
          "ALGOLIA_APP_ID=${{inputs.ALGOLIA_APP_ID }}"
          "ALGOLIA_ID_SEARCH_ONLY_API_KEY=${{ inputs.ALGOLIA_ID_SEARCH_ONLY_API_KEY }}"
          "ALGOLIA_PRIMARY_INDEX=${{inputs.ALGOLIA_PRIMARY_INDEX }}"
          "ALGOLIA_PRIMARY_INDEX_GROUPED=${{inputs.ALGOLIA_PRIMARY_INDEX_GROUPED }}"
          "ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS=${{ inputs.ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS }}"
          "VAPID_PUBLIC_KEY=${{ inputs.VAPID_PUBLIC_KEY }}"
          "VAPID_PRIVATE_KEY=${{ inputs.VAPID_PRIVATE_KEY }}"
          "COMMIT_SHA=${{ github.sha }}"
          "PLANETSCALE_PRISMA_DATABASE_URL_STAGING=${{ env.MY_DB_URL }}${{ inputs.DB_NAME }}"
          "PLANETSCALE_PRISMA_DATABASE_URL_MAIN=${{ env.MY_DB_URL_MAIN }}${{ inputs.DB_NAME }}"
          "SANITY_STUDIO_API_DATASET=${{inputs.SANITY_STUDIO_API_DATASET}}"
          "SANITY_STUDIO_API_PROJECT_ID=${{inputs.SANITY_STUDIO_API_PROJECT_ID}}"
          "SANITY_STUDIO_API_TOKEN=${{inputs.SANITY_STUDIO_API_TOKEN}}"
          "HUBSPOT_ACCESS_TOKEN=${{inputs.HUBSPOT_ACCESS_TOKEN}}"
          "HUBSPOT_PORTAL_ID=${{inputs.HUBSPOT_PORTAL_ID}}"
          "PUBLIC_STOREFRONT_API_TOKEN=${{inputs.PUBLIC_STOREFRONT_API_TOKEN}}"
          "PRIVATE_STOREFRONT_API_TOKEN=${{inputs.PRIVATE_STOREFRONT_API_TOKEN}}"
          "PUBLIC_STOREFRONT_API_VERSION=${{inputs.PUBLIC_STOREFRONT_API_VERSION}}"
          "PUBLIC_STORE_DOMAIN=${{inputs.PUBLIC_STORE_DOMAIN}}"
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # file: ./Dockerfiles/Dockerfile.pr
    - name: 🐳 Docker build PR branch
      uses: docker/build-push-action@v2
      if: ${{ env.PR_CLOSED == 'false' && inputs.BRANCH_NAME }}
      with:
        context: .
        push: true
        tags: registry.fly.io/${{ inputs.APP_NAME }}:${{ env.HEAD_REF }}-${{ github.sha }}
        build-args: |
          "ALGOLIA_APP_ID=${{inputs.ALGOLIA_APP_ID }}"
          "ALGOLIA_ID_SEARCH_ONLY_API_KEY=${{ inputs.ALGOLIA_ID_SEARCH_ONLY_API_KEY }}"
          "ALGOLIA_PRIMARY_INDEX=${{inputs.ALGOLIA_PRIMARY_INDEX }}"
          "ALGOLIA_PRIMARY_INDEX_GROUPED=${{inputs.ALGOLIA_PRIMARY_INDEX_GROUPED }}"
          "ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS=${{ inputs.ALGOLIA_PRIMARY_INDEX_QUERY_SUGGESTIONS }}"
          VAPID_PUBLIC_KEY=${{ inputs.VAPID_PUBLIC_KEY}}
          VAPID_PRIVATE_KEY=${{ inputs.VAPID_PRIVATE_KEY}}
          PLANETSCALE_PRISMA_DATABASE_URL_PR=${{ env.MY_DB_URL }}${{ inputs.DB_NAME }}
          COMMIT_SHA=${{ github.sha }}
          "SANITY_STUDIO_API_DATASET=${{inputs.SANITY_STUDIO_API_DATASET}}"
          "SANITY_STUDIO_API_PROJECT_ID=${{inputs.SANITY_STUDIO_API_PROJECT_ID}}"
          "SANITY_STUDIO_API_TOKEN=${{inputs.SANITY_STUDIO_API_TOKEN}}"
          "HUBSPOT_ACCESS_TOKEN=${{inputs.HUBSPOT_ACCESS_TOKEN}}"
          "HUBSPOT_PORTAL_ID=${{inputs.HUBSPOT_PORTAL_ID}}"
          "PUBLIC_STOREFRONT_API_TOKEN=${{inputs.PUBLIC_STOREFRONT_API_TOKEN}}"
          "PRIVATE_STOREFRONT_API_TOKEN=${{inputs.PRIVATE_STOREFRONT_API_TOKEN}}"
          "PUBLIC_STOREFRONT_API_VERSION=${{inputs.PUBLIC_STOREFRONT_API_VERSION}}"
          "PUBLIC_STORE_DOMAIN=${{inputs.PUBLIC_STORE_DOMAIN}}"
        file: ./Dockerfiles/Dockerfile.pr
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # file: ./Dockerfiles/Dockerfile.pr
    - name: 🐳 Docker build Studio
      uses: docker/build-push-action@v2
      if: ${{ ! inputs.BRANCH_NAME }}
      with:
        context: .
        push: true
        tags: registry.fly.io/${{ inputs.APP_NAME }}:${{ env.HEAD_REF }}-${{ github.sha }}
        build-args: |
          VAPID_PUBLIC_KEY=${{ inputs.VAPID_PUBLIC_KEY}}
          VAPID_PRIVATE_KEY=${{ inputs.VAPID_PRIVATE_KEY}}
          PLANETSCALE_PRISMA_DATABASE_URL_PR=${{ env.MY_DB_URL }}${{ inputs.DB_NAME }}
          COMMIT_SHA=${{ github.sha }}
          "SANITY_STUDIO_API_DATASET=${{inputs.SANITY_STUDIO_API_DATASET}}"
          "SANITY_STUDIO_API_PROJECT_ID=${{inputs.SANITY_STUDIO_API_PROJECT_ID}}"
          "SANITY_STUDIO_API_TOKEN=${{inputs.SANITY_STUDIO_API_TOKEN}}"
          "HUBSPOT_ACCESS_TOKEN=${{inputs.HUBSPOT_ACCESS_TOKEN}}"
          "HUBSPOT_PORTAL_ID=${{inputs.HUBSPOT_PORTAL_ID}}"
        file: ./Dockerfiles/Dockerfile.studio
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

    # This ugly bit is necessary if you don't want your cache to grow forever
    # till it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: 🚚 Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
