// Example of data pulled from a Sanity query
export const mockCardData = {
    _key: '6504cf75da67',
    _type: 'module.cards',
    backgroundColor: 'neutral-200',
    card: [
        {
            _key: 'c3a8ff55fd72',
            _type: 'card.bio',
            reference: {
                _createdAt: '2023-01-24T11:31:02Z',
                _id: 'c863da85-63fc-464f-9c6c-1a5e7168486e',
                _rev: 'plUSZCT0ZgOFXGzkLk9tHh',
                _type: 'team',
                _updatedAt: '2023-01-24T11:34:19Z',
                bio: [
                    {
                        _key: 'e4fcea4d7959',
                        _type: 'block',
                        children: [
                            {
                                _key: '8d224a5c83190',
                                _type: 'span',
                                marks: [],
                                text: 'Samantha is an inspiration to everyone at Open Study College. She has won numerous awards including ‘Influential Women in Business Award’ and ‘Outstanding Business Person’. She has great ambitions for Open Study College’s future including creating partnerships to ensure people across the world have access to education.',
                            },
                        ],
                        markDefs: [],
                        style: 'normal',
                    },
                ],
                image: {
                    _type: 'image.desktop',
                    alt: 'Sam smiling in front of a pink background',
                    image: {
                        _key: 'FBQe_RXB-EVDgGzeXK7ag',
                        _type: 'cloudinary.asset',
                        _version: 1,
                        access_control: [],
                        access_mode: 'public',
                        bytes: 39265,
                        created_at: '2023-01-24T11:33:43Z',
                        created_by: {
                            id: 'd078ed4652231dff007492ab131953',
                            type: 'user',
                        },
                        duration: null,
                        format: 'png',
                        height: 159,
                        metadata: {},
                        public_id: 'Ellipse_11_csazbm',
                        resource_type: 'image',
                        secure_url:
                            'https://res.cloudinary.com/de2iu8gkv/image/upload/v1674560023/Ellipse_11_csazbm.png',
                        tags: [],
                        type: 'upload',
                        uploaded_by: {
                            id: 'd078ed4652231dff007492ab131953',
                            type: 'user',
                        },
                        url: 'http://res.cloudinary.com/de2iu8gkv/image/upload/v1674560023/Ellipse_11_csazbm.png',
                        version: 1674560023,
                        width: 160,
                    },
                },
                name: 'Samantha Rutter',
                role: 'CEO',
            },
        },
        {
            _key: '66f4e0035dcf',
            _type: 'card.course',
            reference: {
                _createdAt: '2022-09-30T10:17:43Z',
                _id: 'shopifyProduct-7438701003007',
                _rev: 'SREtVRJ5tkQiFlHXXWeIQZ',
                _type: 'product',
                _updatedAt: '2023-01-13T11:28:39Z',
                store: {
                    createdAt: '2021-11-08T23:57:17+00:00',
                    descriptionHtml: '<p>Parent product info here.</p>',
                    gid: 'gid://shopify/Product/7438701003007',
                    id: 7438701003007,
                    isDeleted: false,
                    options: [
                        {
                            _key: 'Format',
                            _type: 'option',
                            name: 'Format',
                            values: ['Course Material', 'Course Material + Exams'],
                        },
                        {
                            _key: 'Study-method',
                            _type: 'option',
                            name: 'Study-method',
                            values: ['Study Pack', 'Online'],
                        },
                    ],
                    previewImageUrl:
                        'https://cdn.shopify.com/s/files/1/0609/0519/3727/products/LE018-Microsoft-Office-2013-Training-Bundle_produdctimage-e1599047758747.jpg?v=1636416219',
                    priceRange: {
                        maxVariantPrice: 939,
                        minVariantPrice: 469,
                    },
                    productType: '',
                    slug: {
                        _type: 'slug',
                        current: 'a-level-accounting',
                    },
                    status: 'active',
                    tags: 'Accounting, import_2021_11_08_234706',
                    title: 'A Level Accounting',
                    variants: [
                        {
                            _key: '27849fd3-bccb-586a-9c45-896881757207',
                            _ref: 'shopifyProductVariant-42016897302783',
                            _type: 'reference',
                            _weak: true,
                        },
                        {
                            _key: '17446e53-05c6-54d2-b569-041ede195b91',
                            _ref: 'shopifyProductVariant-42016897335551',
                            _type: 'reference',
                            _weak: true,
                        },
                        {
                            _key: 'f0ab1ef8-ae56-5182-8894-23ab038c8f68',
                            _ref: 'shopifyProductVariant-42016897368319',
                            _type: 'reference',
                            _weak: true,
                        },
                        {
                            _key: '07024074-ee25-53f0-8522-e3e893d55e40',
                            _ref: 'shopifyProductVariant-42016897401087',
                            _type: 'reference',
                            _weak: true,
                        },
                    ],
                    vendor: 'openstudydev',
                },
            },
        },
        {
            _key: '970647996010',
            _type: 'card.collection',
            reference: {
                _createdAt: '2022-09-30T10:19:56Z',
                _id: 'shopifyCollection-387079045375',
                _rev: 'tV53p2YgFcEKyJnroL3tHk',
                _type: 'collection',
                _updatedAt: '2022-09-30T10:19:56Z',
                store: {
                    createdAt: '2022-09-30T10:19:56.409Z',
                    descriptionHtml: '',
                    disjunctive: false,
                    gid: 'gid://shopify/Collection/387079045375',
                    id: 387079045375,
                    isDeleted: false,
                    rules: [
                        {
                            _key: '18c07fa0-e97e-54a7-af3f-76d1135f72bb',
                            _type: 'object',
                            column: 'TAG',
                            condition: 'Accounting',
                            relation: 'EQUALS',
                        },
                    ],
                    slug: {
                        _type: 'slug',
                        current: 'accounting',
                    },
                    sortOrder: 'BEST_SELLING',
                    title: 'Accounting',
                },
            },
        },
        {
            _key: '03a2c6a7b1e1',
            _type: 'card.post',
            reference: {
                _createdAt: '2022-09-28T15:36:12Z',
                _id: '74ed3155-eb70-4938-80bc-4e6747537f9c',
                _rev: 'tV53p2YgFcEKyJnroJERpz',
                _type: 'post',
                _updatedAt: '2022-09-29T14:00:35Z',
                slug: {
                    _type: 'slug',
                    current: 'test-post',
                },
                title: 'Test post',
            },
        },
        {
            _key: '4bf572c00717',
            _type: 'card.static',
            button: {
                _key: '4bf572c00718',
                _type: 'module.button',
                externalLink: {
                    newWindow: true,
                },
                label: 'Copy code',
                textToCopy: 'ALEVELGCSE',
                type: 'copy to clipboard',
                variant: 'primary',
            },
            content: [
                {
                    _key: '79717647465c',
                    _type: 'block',
                    children: [
                        {
                            _key: 'b4772e2352640',
                            _type: 'span',
                            marks: [],
                            text: 'Study three or more A levels or GCSEs to save and start working towards a brighter future.',
                        },
                    ],
                    markDefs: [],
                    style: 'normal',
                },
            ],
            footer: [
                {
                    _key: '710538456043',
                    _type: 'block',
                    children: [
                        {
                            _key: '5543b35dd4fc0',
                            _type: 'span',
                            marks: [],
                            text: 'Offer ends midnight 30th November 2022.',
                        },
                    ],
                    markDefs: [],
                    style: 'normal',
                },
            ],
            heading: 'Enter code ALEVELGCSE to save.',
            image: {
                _type: 'image.desktop',
                alt: 'A Levels or GCSEs £150 off on three or more',
                image: {
                    _key: 'aPmRf8AIKrUGIaMCbohze',
                    _type: 'cloudinary.asset',
                    _version: 1,
                    access_control: [],
                    access_mode: 'public',
                    bytes: 15975,
                    created_at: '2023-01-26T14:16:57Z',
                    created_by: {
                        id: 'd078ed4652231dff007492ab131953',
                        type: 'user',
                    },
                    duration: null,
                    format: 'png',
                    height: 250,
                    metadata: [],
                    public_id: 'Frame_796_kz2zqr',
                    resource_type: 'image',
                    secure_url:
                        'https://res.cloudinary.com/de2iu8gkv/image/upload/v1674742617/Frame_796_kz2zqr.png',
                    tags: [],
                    type: 'upload',
                    uploaded_by: {
                        id: 'd078ed4652231dff007492ab131953',
                        type: 'user',
                    },
                    url: 'http://res.cloudinary.com/de2iu8gkv/image/upload/v1674742617/Frame_796_kz2zqr.png',
                    version: 1674742617,
                    width: 400,
                },
            },
            showFooter: true,
            showSubHeading: true,
            subHeading: 'testst',
        },
    ],
    carouselName: 'List of test cards',
    layout: 'grid',
    rowSettings: {
        backgroundColor: 'neutral-200',
        marginBottom: '',
        paddingBottom: '',
        paddingTop: '',
        container: 'default',
    },
};
