name: "Epic"
description: "Issue for Epics"
title: "[EP1]: "
labels: ["epic"]
body:
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe the Epic."
    validations:
      required: true
