name: "Story"
description: "Issue for User Stories"
title: "[S1.1]: [As a <ROLE>, I want <GOAL/DESIRE> so that <BENEFIT>]"
labels: ["story"]
body:
  - type: input
    id: epic-link-id
    attributes:
      label: "Link to Epic"  
      description: "Add a link below to your github issue epic"
      placeholder: "e.g. Epic: #2"
      value: "Epic: "
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe your story in more detail (if necessary)."
  - type: "textarea"
    id: "task-list"
    attributes:
      label: "Linked Tasks"
      description: |
        List all tasks associated to this story.
      value: |
        - [ ] Task 1 e.g. #1
        - [ ] Task 2 e.g. #2
        - [ ] Task 3 e.g. #3