name: "Task"
description: "Issue for Tasks"
labels: ["task"]
body:
  - type: input
    id: task-link-id
    attributes:
      label: "Link task to story"  
      description: "Add a link to the associated story"
      placeholder: "e.g. Story: #3"
      value: "Story: "
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe your task."
    validations:
      required: true
