name: "setupBuild"
description: "setup node, npm run setup, build osc-ui"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"

    # need to delete all other packages in this step
    - run: npm run setup
      shell: bash

    - run: npm run build:osc-ui
      shell: bash

    - run: npm run copy-fonts:from-ui
      shell: bash