# no ability to accept the (y/n) cli prompt 
# during the Create session secret step in pr-branches.yml
# must point the config file to a toml file wthiout an app name to prevent the prompt from occuring
app = "osc-academic-hub"
kill_signal = "SIGINT"
kill_timeout = 5
processes = [ ]

[env]
  SESSION_SECRET="super-duper-s3cret"

[build]
  dockerfile = "/Dockerfiles/Dockerfile.pr"

[experimental]
allowed_public_ports = [3306]
auto_rollback = true
cmd = "start.sh"
entrypoint = "sh"

[mounts]
source = "data"
destination = "/data"

[[services]]
internal_port = 8080
processes = [ "app" ]
protocol = "tcp"
script_checks = [ ]

  [services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80
  force_https = true

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"

  [[services.http_checks]]
  interval = 10_000
  grace_period = "5s"
  method = "get"
  path = "/healthcheck"
  protocol = "http"
  timeout = 2_000
  tls_skip_verify = false
  headers = { }


[[services]]
  internal_port = 3306
  [[services.ports]]
    handlers = []
    port = 3306
