import type { PortableTextBlock } from '@portabletext/types';
import type { Spacing, Themes } from '../../types';
import type { ButtonProps } from './Content';

interface TextContent {
    backgroundColor?: Themes;
    paddingTop?: Spacing;
    paddingBottom?: Spacing;
    marginBottom?: Spacing;
    body: PortableTextBlock[];
    buttons?: ButtonProps[];
}

// This lovely piece of code is an export of the content data that is generated by Sanity.
// It's pretty large so I've moved it into this file to keep the test & stories a bit tidier.
// It's only really a dependency of the tests & stories and has no impact on the main Content component.
export const textContent: TextContent = {
    body: [
        {
            _key: 'b323c62012f7',
            _type: 'block',
            children: [
                {
                    _key: 'add1ad894075',
                    _type: 'span',
                    marks: [],
                    text: 'Heading 1',
                },
            ],
            markDefs: [],
            style: 'h1',
        },
        {
            _key: '25e75b5aa5d6',
            _type: 'block',
            children: [
                {
                    _key: 'c353d4602892',
                    _type: 'span',
                    marks: [],
                    text: 'Heading 2',
                },
            ],
            markDefs: [],
            style: 'h2',
        },
        {
            _key: '67130c03b412',
            _type: 'block',
            children: [
                {
                    _key: '7ab89b8a8f9c',
                    _type: 'span',
                    marks: [],
                    text: 'Heading 3',
                },
            ],
            markDefs: [],
            style: 'h3',
        },
        {
            _key: '67130c03b413',
            _type: 'block',
            children: [
                {
                    _key: '7ab89b8a8f9c',
                    _type: 'span',
                    marks: [],
                    text: 'Heading 4',
                },
            ],
            markDefs: [],
            style: 'h4',
        },
        {
            _key: '67130c03b414',
            _type: 'block',
            children: [
                {
                    _key: '7ab89b8a8f9c',
                    _type: 'span',
                    marks: [],
                    text: 'Heading 5',
                },
            ],
            markDefs: [],
            style: 'h5',
        },
        {
            _key: '67130c03b415',
            _type: 'block',
            children: [
                {
                    _key: '7ab89b8a8f9c',
                    _type: 'span',
                    marks: [],
                    text: 'Heading 6',
                },
            ],
            markDefs: [],
            style: 'h6',
        },
        {
            _key: 'ae0615968daf',
            _type: 'block',
            children: [
                {
                    _key: '2a9c73ab09540',
                    _type: 'span',
                    marks: [],
                    text: 'Lorem ipsum dolor sit, amet ',
                },
                {
                    _key: '69d0f1d5b5ad',
                    _type: 'span',
                    marks: ['strong'],
                    text: 'consectetur',
                },
                {
                    _key: '20c1cccfb300',
                    _type: 'span',
                    marks: [],
                    text: ' adipisicing elit. Dicta ipsum quos reiciendis maiores voluptatum nihil. ',
                },
                {
                    _key: '8a74442ac941',
                    _type: 'span',
                    marks: ['em'],
                    text: 'Rerum',
                },
                {
                    _key: '2ff620684880',
                    _type: 'span',
                    marks: [],
                    text: ' nobis ea deserunt, incidunt quod ab non quasi repellat itaque consectetur officia in sunt.',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
        {
            _key: 'e38afdc673fc',
            _type: 'block',
            children: [
                {
                    _key: '1e39a513ee7f',
                    _type: 'span',
                    marks: ['fc7211fe8b77'],
                    text: 'Internal link',
                },
            ],
            markDefs: [
                {
                    _key: 'fc7211fe8b77',
                    _type: 'annotationLinkInternal',
                    documentType: 'post',
                    reference: {
                        _ref: '74ed3155-eb70-4938-80bc-4e6747537f9c',
                        _type: 'reference',
                        _weak: true,
                    },
                    slug: '/blog/test-post',
                },
            ],
            style: 'normal',
        },
        {
            _key: '70d2a46f7293',
            _type: 'block',
            children: [
                {
                    _key: 'bc560eb9d24b',
                    _type: 'span',
                    marks: ['fb290b94285a'],
                    text: 'External link',
                },
            ],
            markDefs: [
                {
                    _key: 'fb290b94285a',
                    _type: 'annotationLinkExternal',
                    newWindow: true,
                    url: 'https://example.com',
                },
            ],
            style: 'normal',
        },
        {
            _key: 'ee838d1f79da',
            _type: 'block',
            children: [
                {
                    _key: '1c71ad550385',
                    _type: 'span',
                    marks: ['337c0734cee1'],
                    text: 'Email link',
                },
            ],
            markDefs: [
                {
                    _key: '337c0734cee1',
                    _type: 'annotationLinkEmail',
                    email: 'test@example.com',
                },
            ],
            style: 'normal',
        },
        {
            _key: '0eee0c7ce3c5',
            _type: 'block',
            children: [
                {
                    _key: '4c09a2e3b4e9',
                    _type: 'span',
                    marks: [],
                    text: '',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
        {
            _key: '578279b652c8',
            _type: 'block',
            children: [
                {
                    _key: '9fe2f90fe3b1',
                    _type: 'span',
                    marks: [],
                    text: 'List items',
                },
            ],
            level: 1,
            listItem: 'bullet',
            markDefs: [],
            style: 'normal',
        },
        {
            _key: '88ffa9154b4e',
            _type: 'block',
            children: [
                {
                    _key: 'f303edf120dd',
                    _type: 'span',
                    marks: [],
                    text: 'List items',
                },
            ],
            level: 1,
            listItem: 'bullet',
            markDefs: [],
            style: 'normal',
        },
        {
            _key: 'a7a166ee2f52',
            _type: 'block',
            children: [
                {
                    _key: '31e23068abf8',
                    _type: 'span',
                    marks: [],
                    text: 'List items',
                },
            ],
            level: 1,
            listItem: 'bullet',
            markDefs: [],
            style: 'normal',
        },
        {
            _key: '80b6f50542c1',
            _type: 'block',
            children: [
                {
                    _key: 'b019637320bf',
                    _type: 'span',
                    marks: [],
                    text: 'One',
                },
            ],
            level: 1,
            listItem: 'number',
            markDefs: [],
            style: 'normal',
        },
        {
            _key: '2ee3a1914b62',
            _type: 'block',
            children: [
                {
                    _key: '9b59a473b089',
                    _type: 'span',
                    marks: [],
                    text: 'Two',
                },
            ],
            level: 1,
            listItem: 'number',
            markDefs: [],
            style: 'normal',
        },
        {
            _key: '1a65382b6756',
            _type: 'block',
            children: [
                {
                    _key: '775ec860f180',
                    _type: 'span',
                    marks: [],
                    text: 'Three',
                },
            ],
            level: 1,
            listItem: 'number',
            markDefs: [],
            style: 'normal',
        },
    ],
};

export const textContentHasButtons: TextContent = {
    body: [
        {
            _key: '4da3f0767b0a',
            _type: 'block',
            children: [
                {
                    _key: 'e37a08625abd',
                    _type: 'span',
                    marks: [],
                    text: 'Has Buttons',
                },
            ],
            markDefs: [],
            style: 'h2',
        },
    ],
    buttons: [
        {
            _key: '4e7732fa8971',
            _type: 'module.button',
            externalLink: {
                newWindow: true,
            },
            file: 'https://cdn.sanity.io/files/v6lebos6/staging/bfd009f500c057195ffde66fae64f92fa5f59b72.pdf',
            label: 'File download',
            type: 'file',
        },
        {
            _key: '87d2da567fc3',
            _type: 'module.button',
            email: 'test@example.com',
            externalLink: {
                newWindow: true,
            },
            label: 'Email',
            type: 'email',
        },
        {
            _key: '22c5463fb02a',
            _type: 'module.button',
            externalLink: {
                newWindow: true,
                url: 'https://example.com',
            },
            label: 'External link',
            type: 'external',
        },
        {
            _key: '021e29125841',
            _type: 'module.button',
            externalLink: {
                newWindow: true,
            },
            label: 'Internal link',
            reference: {
                _ref: 'home',
                _type: 'reference',
                _weak: true,
            },
            slug: '/',
            type: 'internal',
        },
        {
            _key: 'b35023227e69',
            _type: 'module.button',
            externalLink: {
                newWindow: true,
            },
            label: 'Telephone',
            telephone: '01234567890',
            type: 'telephone',
        },
        {
            _key: '2a645e6bf859',
            _type: 'module.button',
            externalLink: {
                newWindow: true,
            },
            label: 'Copy to clipboard',
            textToCopy: 'This is copied text',
            type: 'copy to clipboard',
        },
    ],
};

export const textContentWithTextColor: TextContent = {
    body: [
        {
            _key: '055cea62b7f1',
            _type: 'block',
            children: [
                {
                    _key: 'c0acf5edaaff0',
                    _type: 'span',
                    marks: [
                        'span t-font-gamma',
                        'span u-color-gradient-quaternary',
                        'strong u-text-med',
                    ],
                    text: 'Everyone’s journey, whatever that may be, is personal, different, exciting and sometimes difficult. We know that we are in the privileged position of being the enablers of positive, life altering change. We are here to do what we can to help people achieve their goals and thrive in life – we are an expert, a friendly ear, a 24/7 support and a wildly enthusiastic cheerleader!',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
    ],
};

export const textContentSizes: TextContent = {
    body: [
        {
            _key: 'ea7df8dd139a',
            _type: 'block',
            children: [
                {
                    _key: 'df1597a476c10',
                    _type: 'span',
                    marks: ['span t-font-2xs'],
                    text: '2xs',
                },
                {
                    _key: '73012266f0f1',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '48f7519b50d4',
                    _type: 'span',
                    marks: ['span t-font-xs'],
                    text: 'xs',
                },
                {
                    _key: 'f78211c80404',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '70fe2d690d1a',
                    _type: 'span',
                    marks: ['span t-font-s'],
                    text: 's',
                },
                {
                    _key: 'd4c1a45e913d',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '61e4bbd4db60',
                    _type: 'span',
                    marks: ['span t-font-m'],
                    text: 'm',
                },
                {
                    _key: 'd551b5cf0476',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '699dc21e9654',
                    _type: 'span',
                    marks: ['span t-font-l'],
                    text: 'l',
                },
                {
                    _key: '4c126e64eef5',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '03909b3afe21',
                    _type: 'span',
                    marks: ['span t-font-xl'],
                    text: 'xl',
                },
                {
                    _key: '3babf2ee030b',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: 'ceaad69b0e00',
                    _type: 'span',
                    marks: ['span t-font-2xl'],
                    text: '2xl',
                },
                {
                    _key: '16844938fc62',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '125ab9f022bc',
                    _type: 'span',
                    marks: ['span t-font-3xl'],
                    text: '3xl',
                },
                {
                    _key: '10de04979d94',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '0fe32c2a1a96',
                    _type: 'span',
                    marks: ['span t-font-4xl'],
                    text: '4xl',
                },
                {
                    _key: 'bc0f65767fac',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '81d443e81e60',
                    _type: 'span',
                    marks: ['span t-font-5xl'],
                    text: '5xl',
                },
                {
                    _key: '3048bdff37bf',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: '01168998a671',
                    _type: 'span',
                    marks: ['span t-font-6xl'],
                    text: '6xl',
                },
                {
                    _key: '40528d7ac28f',
                    _type: 'span',
                    marks: [],
                    text: '\n',
                },
                {
                    _key: 'fc6724e0193d',
                    _type: 'span',
                    marks: ['span t-font-7xl'],
                    text: '7xl',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
    ],
};

export const textContentFonts: TextContent = {
    body: [
        {
            _key: '6b0ddee623bd',
            _type: 'block',
            children: [
                {
                    _key: '6f41298ed3e9',
                    _type: 'span',
                    marks: ['span t-font-secondary', 'span t-font-6xl'],
                    text: 'Judge',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
        {
            _key: 'be742489a4d9',
            _type: 'block',
            children: [
                {
                    _key: '605995e34058',
                    _type: 'span',
                    marks: ['span t-font-primary', 'span t-font-4xl'],
                    text: 'Outfit',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
    ],
};

export const textContentWithBackgroundColor: TextContent = {
    backgroundColor: 'quinary',
    body: [
        {
            _key: '055cea62b7f1',
            _type: 'block',
            children: [
                {
                    _key: 'c0acf5edaaff0',
                    _type: 'span',
                    marks: [
                        'span t-font-2xl',
                        'span u-color-gradient-quaternary',
                        'strong u-text-med',
                    ],
                    text: 'Everyone’s journey, whatever that may be, is personal, different, exciting and sometimes difficult. We know that we are in the privileged position of being the enablers of positive, life altering change. We are here to do what we can to help people achieve their goals and thrive in life – we are an expert, a friendly ear, a 24/7 support and a wildly enthusiastic cheerleader!',
                },
            ],
            markDefs: [],
            style: 'normal',
        },
    ],
    paddingBottom: 's',
    paddingTop: 's',
};
