import type { HubspotFormFieldGroups } from './types';

export const contactFormData = {
    formFieldGroups: [
        {
            fields: [
                {
                    name: 'email',
                    label: 'Email',
                    type: 'string',
                    fieldType: 'text',
                    description: '',
                    groupName: 'contactinformation',
                    displayOrder: -1,
                    required: true,
                    selectedOptions: [],
                    options: [],
                    validation: {
                        name: '',
                        message: '',
                        data: '',
                        useDefaultBlockList: false,
                        blockedEmailAddresses: [],
                    },
                    enabled: true,
                    hidden: false,
                    defaultValue: '',
                    isSmartField: false,
                    unselectedLabel: '',
                    placeholder: 'Your email address',
                    dependentFieldFilters: [],
                    labelHidden: false,
                    propertyObjectType: 'CONTACT',
                    metaData: [],
                    objectTypeId: '0-1',
                },
            ],
            default: true,
            isSmartGroup: false,
            richText: { content: '', type: 'TEXT' },
            isPageBreak: false,
        },
        {
            fields: [
                {
                    name: 'firstname',
                    label: 'First name',
                    type: 'string',
                    fieldType: 'text',
                    description: '',
                    groupName: 'contactinformation',
                    displayOrder: -1,
                    required: true,
                    selectedOptions: [],
                    options: [],
                    validation: {
                        name: '',
                        message: '',
                        data: '',
                        useDefaultBlockList: false,
                        blockedEmailAddresses: [],
                    },
                    enabled: true,
                    hidden: false,
                    defaultValue: '',
                    isSmartField: false,
                    unselectedLabel: '',
                    placeholder: 'Your first name',
                    dependentFieldFilters: [],
                    labelHidden: false,
                    propertyObjectType: 'CONTACT',
                    metaData: [],
                    objectTypeId: '0-1',
                },
            ],
            default: true,
            isSmartGroup: false,
            richText: { content: '', type: 'TEXT' },
            isPageBreak: false,
        },
        {
            fields: [
                {
                    name: 'lastname',
                    label: 'Last name',
                    type: 'string',
                    fieldType: 'text',
                    description: '',
                    groupName: 'contactinformation',
                    displayOrder: -1,
                    required: true,
                    selectedOptions: [],
                    options: [],
                    validation: {
                        name: '',
                        message: '',
                        data: '',
                        useDefaultBlockList: false,
                        blockedEmailAddresses: [],
                    },
                    enabled: true,
                    hidden: false,
                    defaultValue: '',
                    isSmartField: false,
                    unselectedLabel: '',
                    placeholder: 'Your last name',
                    dependentFieldFilters: [],
                    labelHidden: false,
                    propertyObjectType: 'CONTACT',
                    metaData: [],
                    objectTypeId: '0-1',
                },
            ],
            default: true,
            isSmartGroup: false,
            richText: { content: '', type: 'TEXT' },
            isPageBreak: false,
        },
        {
            fields: [
                {
                    name: 'phone',
                    label: 'Phone number',
                    type: 'string',
                    fieldType: 'phonenumber',
                    description: '',
                    groupName: 'contactinformation',
                    displayOrder: -1,
                    required: true,
                    selectedOptions: [],
                    options: [],
                    validation: {
                        name: '',
                        message: '',
                        data: '7:20:true',
                        useDefaultBlockList: false,
                        blockedEmailAddresses: [],
                    },
                    enabled: true,
                    hidden: false,
                    defaultValue: '',
                    isSmartField: false,
                    unselectedLabel: '',
                    placeholder: 'Your phone number',
                    dependentFieldFilters: [],
                    labelHidden: false,
                    propertyObjectType: 'CONTACT',
                    metaData: [],
                    objectTypeId: '0-1',
                },
            ],
            default: true,
            isSmartGroup: false,
            richText: { content: '', type: 'TEXT' },
            isPageBreak: false,
        },
        {
            fields: [
                {
                    name: 'message',
                    label: 'Message',
                    type: 'string',
                    fieldType: 'textarea',
                    description: '',
                    groupName: 'contact_activity',
                    displayOrder: -1,
                    required: true,
                    selectedOptions: [],
                    options: [],
                    validation: {
                        name: '',
                        message: '',
                        data: '',
                        useDefaultBlockList: false,
                        blockedEmailAddresses: [],
                    },
                    enabled: true,
                    hidden: false,
                    defaultValue: '',
                    isSmartField: false,
                    unselectedLabel: '',
                    placeholder: '',
                    dependentFieldFilters: [],
                    labelHidden: false,
                    propertyObjectType: 'CONTACT',
                    metaData: [],
                    objectTypeId: '0-1',
                },
            ],
            default: true,
            isSmartGroup: false,
            richText: { content: '', type: 'TEXT' },
            isPageBreak: false,
        },
    ] as HubspotFormFieldGroups[],
    validationErrors: {
        email: ['Invalid Email'],
        firstname: ['Field is required'],
        lastname: ['Field is required'],
        phone: ['Field is required'],
        message: ['Field is required'],
    },
};
