import './styles/main.scss';
export { Header } from './components/Header/Header';
export { Footer } from './components/Footer/Footer';
export { Tabs } from './components/Tabs/Tabs';
export { Badge } from './components/Badge/Badge';
export { Trustpilot } from './components/Trustpilot/Trustpilot';
export { Carousel } from './components/Carousel/Carousel';
export { OSCModal as Modal } from './components/Modal/Modal';
export { Tag } from './components/Tag/Tag';
export { Breadcrumb } from './components/Breadcrumb/Breadcrumb';
