# .github/workflows/chromatic.yml

# Workflow name
name: "Chromatic"

# Event for the workflow
on: push

# List of jobs
jobs:
  pre-check:
    name: check if workflow should run
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            osc-academic-hub:
              - 'packages/osc-academic-hub/**'
            osc-ui:
              - 'packages/osc-ui/**'
            osc-workflows:
              - '.github/workflow/osc-academic-hub/**'
        # run only if some file in 'src' folder was changed
      - if: steps.changes.outputs.src == 'false'
        run: exit 1

  chromatic-deployment:
    needs: pre-check
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3

      - run: rm -v -r ./package.json ./.storybook
      - run: mkdir ./.storybook
      - run: mkdir ./prisma
      - run: mv -v -f packages/osc-academic-hub/* .
      - run: mv -v -f packages/osc-academic-hub/.storybook/* ./.storybook

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm run addDevDeps

      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing
