name: Delete all pscale passwords to staging and main

on: workflow_dispatch

env:
  pscale_base_directory: .pscale

jobs:
  delete-all-passwords:
    name: "Delete all passwords"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Delete all passwords to staging
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          BRANCH_NAME: staging
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: ./create-database.sh

      - name: Delete all passwords to main
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{secrets.PLANETSCALE_SERVICE_TOKEN_ID}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          BRANCH_NAME: main
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: ./create-database.sh
