name: Main App
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: iad

jobs:
  destroy_staging_app:
    runs-on: ubuntu-latest

    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v2

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "fly.toml"
          field: "app"

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps destroy pr-${{ github.event.number }}-${{ steps.app_name.outputs.value }} -y
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
