name: Destroy pr app
on:
  pull_request:
    types: [closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: iad

jobs:
  pre-check:
    name: check if workflow should run
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - if: github.event.pull_request.draft == true
        name: Cancel the self CI workflow run
        run: ./workflow-scripts/cancel.sh

  destroy_staging_app:
    runs-on: ubuntu-latest
    needs: pre-check
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3

      - name: movePackageToRoot
        uses: ./.github/actions/movePackageToRoot
        id: movePackageToRoot
        with:
          name: "osc-studio"

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: "fly.toml"
          field: "app"

      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: always()
        continue-on-error: true
      - run: flyctl apps destroy pr-${{ github.event.number }}-${{ steps.app_name.outputs.value }} -y
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
