name: PR Branch App for osc-ecommerce
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: iad

jobs:
  pre-check:
    name: check if workflow should run
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            composite-actions:
              - '.github/actions/**'
            osc-api-auth: 
              - 'packages/osc-api-auth/**'
            osc-ecommerce:
              - 'packages/osc-ecommerce/**'
            Dockerfiles:
              - 'Dockerfiles/**'
            osc-ecommerce-deploy:
              - '.github/workflows/osc-ecommerce-deploy.yml'
            osc-ecommerce-destroy-apps:
              - '.github/workflows/osc-ecommerce-destroy-apps.yml'
            osc-ecommerce-pr:
              - '.github/workflows/osc-ecommerce-pr-branches.yml'

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - if: steps.changes.outputs.changes == '[]' || github.event.pull_request.draft == true
        name: Cancel the self CI workflow run
        run: ./workflow-scripts/cancel.sh

  build:
    needs: pre-check
    name: 🐳 Build PR Branch
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: setupBuild
        uses: ./.github/actions/setupBuild
        id: setupBuild

      - name: movePackageToRoot
        uses: ./.github/actions/movePackageToRoot
        id: movePackageToRoot
        with:
          name: "osc-ecommerce"

      - name: readAndLogAppNameAndBranch
        uses: ./.github/actions/readAndLogAppNameAndBranch
        id: readAndLogAppNameAndBranch

      - name: dockerBuild
        uses: ./.github/actions/dockerBuild
        id: dockerBuild
        with:
          PASSWORD_NAME: pr-${{ github.event.number }}-${{ steps.readAndLogAppNameAndBranch.outputs.app-name }}
          APP_NAME: ${{ steps.readAndLogAppNameAndBranch.outputs.app-name }}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          BRANCH_NAME: staging
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY}}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY}}
          SANITY_STUDIO_API_DATASET: ${{secrets.SANITY_STUDIO_API_DATASET}}
          SANITY_STUDIO_API_PROJECT_ID: ${{secrets.SANITY_STUDIO_API_PROJECT_ID}}
          SANITY_STUDIO_API_TOKEN: ${{secrets.SANITY_STUDIO_API_TOKEN}}
          HUBSPOT_ACCESS_TOKEN: ${{secrets.HUBSPOT_ACCESS_TOKEN}}
          HUBSPOT_PORTAL_ID: ${{secrets.HUBSPOT_PORTAL_ID}}
  deploy:
    needs: build
    name: 🚀 Deploy PR Branch
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}-ecommerce-pr

    # Create a GitHub deployment environment per pr branch app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy_pr.outputs.url }}

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: setupBuild
        uses: ./.github/actions/setupBuild
        id: setupBuild

      - name: movePackageToRoot
        uses: ./.github/actions/movePackageToRoot
        id: movePackageToRoot
        with:
          name: "osc-ecommerce"

      - name: readAndLogAppNameAndBranch
        uses: ./.github/actions/readAndLogAppNameAndBranch
        id: readAndLogAppNameAndBranch

      - name: deployment
        uses: ./.github/actions/deployment
        id: deployment
        with:
          APP_NAME: ${{ steps.readAndLogAppNameAndBranch.outputs.app-name }}
          FLY_PR_BRANCH_SESSION_SECRET: ${{ secrets.FLY_PR_BRANCH_SESSION_SECRET}}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN}}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
