name: 🚀 Deploy osc-studio
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
permissions:
  actions: write
  contents: read

jobs:
  pre-check:
    name: check if workflow should run
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            osc-studio:
              - 'packages/osc-studio/**'
            osc-studio-deploy:
              - '.github/workflows/osc-studio-deploy.yml'
            osc-studio-pr:
              - '.github/workflows/osc-studio-pr-branches.yml'
        # run only if some file in 'src' folder was changed

      - name: Get PR details
        run: |
          echo "${{ github.base_ref }} == main && ${{ github.event.pull_request.merged }} == true"
          echo "BASE_REF=${{ github.base_ref  }}" >> $GITHUB_ENV
          echo "PR_CLOSED=${{ github.event.pull_request.merged == true }}" >> $GITHUB_ENV

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - if: steps.changes.outputs.changes == '[]' || github.event.pull_request.draft == true
        name: Cancel the self CI workflow run
        run: ./workflow-scripts/cancel.sh

  build:
    name: 🐳 Build
    if: echo "${{ github.base_ref }} == main && ${{ github.event.pull_request.merged }} == true"
    needs: pre-check
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: checkoutCancelSetupBuild
        uses: ./.github/actions/checkoutCancelSetupBuild
        id: checkoutCancelSetupBuild
        with:
          name: "osc-studio"

      - name: readAndLogAppNameAndBranch
        uses: ./.github/actions/readAndLogAppNameAndBranch
        id: readAndLogAppNameAndBranch

      - name: dockerBuild
        uses: ./.github/actions/dockerBuild
        id: dockerBuild
        with:
          APP_NAME: ${{ steps.readAndLogAppNameAndBranch.outputs.app-name }}
          BRANCH: ${{ steps.readAndLogAppNameAndBranch.outputs.branch }}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY}}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY}}
          SANITY_STUDIO_API_DATASET: ${{secrets.SANITY_STUDIO_API_DATASET}}
          SANITY_STUDIO_API_PROJECT_ID: ${{secrets.SANITY_STUDIO_API_PROJECT_ID}}
          SANITY_STUDIO_API_TOKEN: ${{secrets.SANITY_STUDIO_API_TOKEN}}

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: checkoutCancelSetupBuild
        uses: ./.github/actions/checkoutCancelSetupBuild
        id: checkoutCancelSetupBuild
        with:
          name: "osc-studio"

      - name: readAndLogAppNameAndBranch
        uses: ./.github/actions/readAndLogAppNameAndBranch
        id: readAndLogAppNameAndBranch

      - name: deployment
        uses: ./.github/actions/deployment
        id: deployment
        with:
          APP_NAME: ${{ steps.readAndLogAppNameAndBranch.outputs.app-name }}
          BRANCH: ${{ steps.readAndLogAppNameAndBranch.outputs.branch }}
          FLY_PR_BRANCH_SESSION_SECRET: ${{ secrets.FLY_PR_BRANCH_SESSION_SECRET}}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN}}
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
