#
# This workflow takes care of creating a database branch and a password for it in PlanetScale.
#

name: 💽 Create Database Branch

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string

permissions:
  actions: write
  pull-requests: write
  contents: read

jobs:
  create_a_branch:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🎋 Create a branch
        uses: planetscale/create-branch-action@v1
        id: create_branch
        with:
          org_name: ${{secrets.ORG_NAME}}
          database_name: ${{secrets.DB_NAME}}
          branch_name: staging
          from: main
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}

      - name: 🔒 Create a password
        uses: planetscale/create-branch-password-action@v1
        id: create_branch_password
        with:
          org_name: ${{secrets.ORG_NAME}}
          database_name: ${{secrets.DB_NAME}}
          branch_name: staging
          name: 'staging-pr-${{ github.event.number }}-${{inputs.app_name}}'
        env:
          PLANETSCALE_SERVICE_TOKEN_ID: ${{ secrets.PLANETSCALE_SERVICE_TOKEN_ID }}
          PLANETSCALE_SERVICE_TOKEN: ${{ secrets.PLANETSCALE_SERVICE_TOKEN }}

      - name: Get the new credentials
        run: |
          echo "Hostname: ${{ steps.create_branch_password.outputs.hostname }}"
          echo "Username: ${{ steps.create_branch_password.outputs.username }}"
          echo "Password: ${{ steps.create_branch_password.outputs.password }}"